=== juletx/iragarkiak/xml/Questions.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="assessmentItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="assessmentItem" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="itemBody">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="p"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="correctResponse">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="value"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="incorrectResponses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="value" maxOccurs="3" minOccurs="3"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="author" use="required"/>
            <xs:attribute type="xs:string" name="subject" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== juletx/iragarkiak/xml/Questions.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../xml/ShowXmlQuestions.xsl"?>
<assessmentItems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Questions.xsd">
	<assessmentItem author="rosa.arruabarrena@ehu.eus" subject="Mikologia">
		<itemBody>
			<p>Zein Amanita da jangarria?</p>
		</itemBody>
		<correctResponse>
			<value>Caesarea</value>
		</correctResponse>
		<incorrectResponses>
			<value>Phalloides</value>
			<value>Muscaria</value>
			<value>Virosa</value>
		</incorrectResponses>
	</assessmentItem>
	<assessmentItem author="vadillo@ehu.es" subject="Mikologia">
		<itemBody>
			<p>Tripakiek zer dute kapela azpian?</p>
		</itemBody>
		<correctResponse>
			<value>Eztenak</value>
		</correctResponse>
		<incorrectResponses>
			<value>Filamenduak</value>
			<value>Himenioa</value>
			<value>Hodiak</value>
		</incorrectResponses>
	</assessmentItem>
	<assessmentItem author="mafalda001@ikasle.ehu.eus" subject="Mikologia">
		<itemBody>
			<p>Eranztuna du</p>
		</itemBody>
		<correctResponse>
			<value>Galanpernak</value>
		</correctResponse>
		<incorrectResponses>
			<value>Gibel urdinak</value>
			<value>Esnegorriak</value>
			<value>Errotariak</value>
		</incorrectResponses>
	</assessmentItem>
</assessmentItems>
